name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --legacy-peer-deps

      # Build the projects
      - run: |
          npx nx build frontend --verbose
          npx nx build horse-betting --verbose

      # Lint the projects
      - run: |
          npx nx lint frontend
          npx nx lint horse-betting

      # Run unit tests for the projects
      - run: |
          npx nx test frontend --coverage
          npx nx test horse-betting --coverage

      # Install Playwright Browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Verify Playwright Browsers Installation
      - name: Verify Playwright Installation
        run: ls -la ~/.cache/ms-playwright/

      # Start the server and run E2E tests for frontend
      - name: Start Server and Run E2E Tests for Frontend
        run: |
          npx nx serve frontend &
          sleep 10 # Ensure the server has time to start
          npx playwright test

      # Start the server and run E2E tests for horse-betting
      - name: Start Server and Run E2E Tests for Horse Betting
        run: |
          npx nx serve horse-betting &
          sleep 10 # Ensure the server has time to start
          npx playwright test
