name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --legacy-peer-deps

      # Build the project
      - run: npx nx build frontend

      # Run the custom script to start the server and run Playwright tests
      - name: Run E2E Tests
        run: npx ts-node start-server-and-test.ts

      # Optionally, stop Nx Cloud agents after E2E tests
      - run: npx nx-cloud stop-agents